using Microsoft.Extensions.DependencyInjection;
using ZealTravel.Application.Handlers;
using AutoMapper;
using ZealTravel.Application.Mappers;
using ZealTravel.Domain.Interfaces.IRepository;
using ZealTravel.Domain.Interfaces.Handlers;
using ZealTravel.Application.UserManagement.Queries;
using ZealTravel.Domain.Data.Entities;
using ZealTravel.Application.AgencyManagement.Queries;
using ZealTravel.Application.AgencyManagement.Handlers;
using ZealTravel.Domain.AgencyManagement;
using ZealTravel.Infrastructure.Services;
using System.Configuration;
using Microsoft.Extensions.Configuration;
using ZealTravel.Common.Services;
using ZealTravel.Application.UserManagement.Commands;
using ZealTravel.Application.UserManagement.Handlers;
using ZealTravel.Domain.Services;
using ZealTravel.Application.AgencyManagement.Command;
using ZealTravel.Application.AirlineManagement.Queries;
using ZealTravel.Application.AirlineManagement.Handler;
using ZealTravel.Domain.Interfaces.Services;
using ZealTravel.Domain.Data.Models;
using ZealTravel.Application.AgencyManagement.Handlers.AgencyDashboard;
using ZealTravel.Application.AgencyManagement.Queries.AgencyDashboard;
using ZealTravel.Application.ReportManagement.Handler;
using ZealTravel.Application.ReportManagement.Queries;
using ZealTravel.Application.AirlineSupplierManagement.Queries;
using ZealTravel.Application.AirlineSupplierManagement.Handlers;
using ZealTravel.Infrastructure.Services.Agency;
using ZealTravel.Domain.Interfaces.AirlineSupplierManagement;
using ZealTravel.Application.BackofficeManagement.Queries.Dashboard;
using ZealTravel.Application.BackofficeManagement.Handlers.Dashboard;
using ZealTravel.Domain.Interfaces.Backoffice;
using ZealTravel.Infrastructure.Services.Backoffice;
using ZealTravel.Application.BankManagement.Handler;
using ZealTravel.Application.BankManagement.Query;
using ZealTravel.Application.BankManagement.Command;
using ZealTravel.Application.BookingManagement.Query;
using ZealTravel.Application.BookingManagement.Handler;
using ZealTravel.Domain.BookingManagement;
using ZealTravel.Application.CredentialManagement.Handlers;
using ZealTravel.Application.CredentialManagement.Query;
using ZealTravel.Application.CredentialManagement.Command;
using ZealTravel.Application.DBCommonManagement.Commands;
using ZealTravel.Domain.Interfaces.DBCommon;
using ZealTravel.Infrastructure.Services.DBLogger;
namespace ZealTravel.Backoffice.Web.Extensions
{
    public static class HandlersConfig
    {
        public static IServiceCollection AddCustomServices(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddScoped<IHandlesQueryAsync<GetUserDetailsQuery, CompanyRegister>, GetUserDetailsQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<GetAvailableBalanceQuery, decimal>, GetAvailableBalanceQueryHandler>();
            services.AddScoped<IAgencyService, AgencyService>();
            services.AddScoped<IUserService, UserService>();
            EmailService.Configure(configuration);
            services.AddSingleton<EmailService>();
            services.AddScoped<IHandlesCommandAsync<ForgotPasswordCommand>, ForgetPasswordCommandHandler>();
            services.AddScoped<IHandlesCommandAsync<RegisterUserCommand>, RegisterUserCommandHandler>();
            services.AddScoped<UserManagementService>();
            services.AddScoped<IHandlesQueryAsync<GetCitySearchTermQuery, List<string>>, GetCitylistQueryHandler>();
            services.AddTransient<IHandlesCommandAsync<ChangePasswordCommand>, ChangePasswordCommandHandler>();
            services.AddScoped<IGstStateCityService, GstStateCityService>();
            services.AddScoped<GetCitiesByStateQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<GetStatesQuery, List<GstStates>>, GetStatesQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<GetCitiesByStateQuery, List<CityState>>, GetCitiesByStateQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<DailyBookingReportsQuery, List<DailyBooking>>, DailyBookingQueryHandler>();
            services.AddScoped<IReportingService, ReportingService>();
            services.AddScoped<IAirlineSupplierService, AirSupplierService>();
            services.AddScoped<IAgencyDashboardService, AgencyDashboardService>();
            services.AddScoped<IBankService, BankService>();
            services.AddScoped<IHandlesQueryAsync<GetCitySearchTermQuery, List<string>>, GetCitylistQueryHandler>();
            services.AddTransient<IHandlesCommandAsync<ChangePasswordCommand>, ChangePasswordCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<GetProfileQuery, CompanyProfileData>, GetProfileQueryHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateLogoCommand>, UpdateLogoCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<LedgerReportQuery, List<LedgerReports>>, LedgerReportQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<AirBookingQuery, List<AirBookingReport>>, AirBookingQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<DashboardLedgerQuery, List<DashboardLedgerData>>, DashboardLedgerQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<DashboardNotificationQuery, List<DashboardNotificationData>>, DashboardNoticeQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<DashboardChartQuery, List<DashboardChartData>>, DashboardChartQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<DashboardCorporateQuery, List<DashboardCorporateData>>, DashboardCorporateQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<CompanyIdByAccountIdQuery, string>, GetCompanyIDByAccountIDQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<AgencyListBySearchTextQuery, List<string>>, GetAgencyListbySerachTextQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<SearchAgencyTextQuery, List<SearchAgencyListData>>, SearchAgencyBySearchTextQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<GetAirSupplierQuery, List<AirSupplier>>, GetAirSupplierQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<CancelAirBookingReportsQuery, List<CancelAirBooking>>, CanelAirBookingQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<List<DashboardAirlinePendingBookingData>>, DashboardAirlinePendingBookingQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<DashboardAirlinetopTenBookingQuery, List<DashboardAirlineTopTenBookingData>>, DashboardAirlinetopTenBookingQueryHandler>();
            services.AddScoped<IDashboardService, DashboardService>();
            services.AddScoped<IHandlesQueryAsync<GetCompanyPopupDetailsQuery, CompanyPopupDetails>, GetCompanyPopupDetailsQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<GetCompanyProfileQuery, CompanyProfileData>, GetCompanyProfileHandler>();
            services.AddScoped<IHandlesCommandAsync<CompanyProfileCommand>, CompanyProfileCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<GetBankDetailQuery, List<AdminBankDetails>>, GetBankDetailQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<BankNameQuery, List<GetBankNameQuery>>, GetBankNameQueryHandler>();
            services.AddScoped<GetBankDetailQueryHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateBankCommand>, UpdateBankDetailCommandHandler>();
            services.AddScoped<IHandlesCommandAsync<BankDetailCommand>, AddBankDetailCommandHandler>();
            services.AddScoped<DeleteBankDetailHandler>();
            services.AddScoped<IHandlesQueryAsync<CompanyIdByAccountIdQuery, string>, GetCompanyIDByAccountIDQueryHandler>();
            services.AddKeyedScoped<IHandlesQueryAsync<int, bool>, GetBookingPnrStatusHandler>("BookingPnrStatusHandler");
            services.AddKeyedScoped<IHandlesQueryAsync<int, bool>, GetTicketStatusHandler>("TicketStatusHandler");
            services.AddScoped<IHandlesQueryAsync<GetCompanyDetailsAfterLoginQuery, List<CompanyAfterLoginDetails>>, GetCompanyDetailsAfterLoginHandler>();
            services.AddScoped<IHandlesQueryAsync<List<GalelioSupplierAirline>>, GetGalelioSupplierHandler>();
            services.AddScoped<IHandlesQueryAsync<BookingDetailQuery, BookingDetailData>, BookingTicketQueryHandler>();
            services.AddScoped<IBookingManagementService, BookingService>();
            services.AddScoped<IHandlesCommandAsync<UpdateBalanceTransactionCommand>, UpdateBalanceTransactionCommandHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateGalelioCommand>, UpdateGalelioCommandHandler>();
            services.AddTransient<IHandlesQueryAsync<GetAgencyBalanceTransactionEventQuery, List<GetAgencyBalanceTransactionEvents>>, GetAgencyBalanceTransactionEventsHandler>();
            services.AddScoped<IHandlesQueryAsync<VerifyAgentBookingQuery, bool>, VerifyAgentQueryHandler>();
            services.AddScoped<IHandlesQueryAsync<List<LccSupplierAirline>>, GetLccAirlineHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateLccAirlineCommand>, UpdateLccAirlineCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<List<AirlineApiDetails>>, GetAirlineApiHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateAirlineApiCommand>, UpdateAirlineApiCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<VerifyAgentBookingQuery, bool>, VerifyAgentQueryHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateUapiCcCommand>, UpdateUapiCcHandler>();
            services.AddScoped<IHandlesQueryAsync<List<UapiCcDetails>>, GetUapiCcHandler>();
            services.AddScoped<IHandlesCommandAsync<int>, DeleteUapiCcHandler>();
            services.AddScoped<IHandlesQueryAsync<List<UapiFopDetail>>, GetUapiFopHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateUapiFopCommand>, UpdateUapiCommandHandler>();
            services.AddScoped<IHandlesCommandAsync<SupplierProductDetailCommand>, UpdateProductDetailCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<List<SupplierCredProductDetails>>, GetSupplierProductDetailHandler>();
            services.AddScoped<IHandlesCommandAsync<PnrMakeDaysCommand>, UpdatePnrMakeDaysHandler>();
            services.AddScoped<IHandlesQueryAsync<List<PnrMakeDaysDetails>>, GetPnrMakeDaysHandler>();
            services.AddScoped<IHandlesCommandAsync<int>, DeletePnrMakeDaysHandler>();
            services.AddScoped<IHandlesCommandAsync<UpdateProductStatusCommand>, UpdateProductStatusCommandHandler>();
            services.AddScoped<IHandlesQueryAsync<List<ProductStatusDetails>>, GetSupplierProductStatusHandler>();
            services.AddScoped<IHandlesCommandAsync<InsertUapiCcCommand>, InsertUapiCcHandler>();
            services.AddScoped<IHandlesCommandAsync<InsertPnrMakeDaysCommand>, InsertPnrMakeDaysHandler>();
            services.AddKeyedScoped<IHandlesCommandAsync<int>, DeleteUapiCcHandler>("DeleteUapiCc");
            services.AddKeyedScoped<IHandlesCommandAsync<int>, DeletePnrMakeDaysHandler>("DeletePnrMakeDays");
            services.AddTransient<IHandlesQueryAsync<AirBookingDetailQuery, AirSheetReportData>, AirSheetReportQueryHandler>();
            services.AddKeyedScoped<IHandlesQueryAsync<BookingRefrenceQuery, List<FlightBookingRefrence>>, GetFlightRefrenceHandler>("FlightReference");
            services.AddKeyedScoped<IHandlesQueryAsync<CancelAirRefrenceQuery, List<FlightBookingRefrence>>, GetCancelRefundReportHandler>("CancelRefund");
            services.AddScoped<IHandlesCommandAsync<AddDBLogCommand>, AddDbLogCommandHandler>();
            services.AddScoped<IHandlesCommandAsync<AddDBSearchLogCommand>, AddDbSearchLogCommandHandler>();
            services.AddScoped<IDBLoggerService, DBLoggerService>();
            return services;
        }
    }
} 