using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZealTravel.Common.Models
{
    public class AirlineAvailabilityInfo
    {
        public int RowID { get; set; }
        public string AirlineID { get; set; }
        public string FlightID { get; set; }
        public int RefID { get; set; }
        public int OrderNo { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string CarrierName { get; set; }
        public string CarrierCode { get; set; }
        public string FlightNumber { get; set; }
        public string DepartureStation { get; set; }
        public string ArrivalStation { get; set; }
        public string DepartureDate { get; set; }
        public string ArrivalDate { get; set; }
        public string DepartureTime { get; set; }
        public string ArrivalTime { get; set; }
        public string FareQuote { get; set; }
        public string ClassOfService { get; set; }
        public string FltType { get; set; }
        public int Stops { get; set; }
        public string Via { get; set; }
        public string ViaName { get; set; }
        public int SeatsAvailable { get; set; }
        public int Adt { get; set; }
        public int Chd { get; set; }
        public int Inf { get; set; }
        public int AdtTotalBasic { get; set; }
        public int AdtTotalTax { get; set; }
        public int AdtTotalFare { get; set; }
        public int ChdTotalBasic { get; set; }
        public int ChdTotalTax { get; set; }
        public int ChdTotalFare { get; set; }
        public int InfTotalBasic { get; set; }
        public int InfTotalTax { get; set; }
        public int InfTotalFare { get; set; }
        public int TotalFare { get; set; }
        public int TotalBasic { get; set; }
        public int TotalTax { get; set; }
        public int TotalServiceTax { get; set; }
        public int TotalServiceFee { get; set; }
        public int TotalMarkup { get; set; }
        public int TotalCommission { get; set; }
        public int TotalCommission_SA { get; set; }
        public int TotalTds { get; set; }
        public int TotalTds_SA { get; set; }
        public string SA_deal { get; set; }
        public int TotalCfee { get; set; }
        public int Adt_BASIC { get; set; }
        public int Adt_YQ { get; set; }
        public int Adt_PSF { get; set; }
        public int Adt_UDF { get; set; }
        public int Adt_AUDF { get; set; }
        public int Adt_CUTE { get; set; }
        public int Adt_GST { get; set; }
        public int Adt_TF { get; set; }
        public int Adt_CESS { get; set; }
        public int Adt_EX { get; set; }
        public int Chd_BASIC { get; set; }
        public int Chd_YQ { get; set; }
        public int Chd_PSF { get; set; }
        public int Chd_UDF { get; set; }
        public int Chd_AUDF { get; set; }
        public int Chd_CUTE { get; set; }
        public int Chd_GST { get; set; }
        public int Chd_TF { get; set; }
        public int Chd_CESS { get; set; }
        public int Chd_EX { get; set; }
        public int Inf_BASIC { get; set; }
        public int Inf_TAX { get; set; }
        public int TotalSeat { get; set; }
        public int TotalMeal { get; set; }
        public int TotalBaggage { get; set; }
        public int TotalImport { get; set; }
        public int Adt_ST { get; set; }
        public int Adt_TDS { get; set; }
        public int Adt_SF { get; set; }
        public int Adt_Import { get; set; }
        public int Adt_BAS { get; set; }
        public int Adt_Y { get; set; }
        public int Adt_CB { get; set; }
        public int Adt_PR { get; set; }
        public int Adt_MU { get; set; }
        public int Chd_ST { get; set; }
        public int Chd_TDS { get; set; }
        public decimal Chd_Import { get; set; }
        public int Chd_SF { get; set; }
        public int Chd_BAS { get; set; }
        public int Chd_Y { get; set; }
        public int Chd_CB { get; set; }
        public int Chd_PR { get; set; }
        public int Chd_MU { get; set; }
        public string JourneyTimeDesc { get; set; }
        public string DurationDesc { get; set; }
        public DateTime DepDate { get; set; }
        public DateTime ArrDate { get; set; }
        public DateTime DepTime { get; set; }
        public DateTime ArrTime { get; set; }
        public string ProductClass { get; set; }
        public string PriceType { get; set; }
        public string DepartureTerminal { get; set; }
        public string ArrivalTerminal { get; set; }
        public string Classes { get; set; }
        public string FareBasisCode { get; set; }
        public bool ValidFBCode { get; set; }
        public bool FareStatus { get; set; }
        public bool IsPriceChanged { get; set; }
        public string Cabin { get; set; }
        public string EquipmentType { get; set; }
        public string RuleNumber { get; set; }
        public string RuleTarrif { get; set; }
        public string RefundType { get; set; }
        public string FareRuledb { get; set; }
        public string BaggageDetail { get; set; }
        public int AG_Markup { get; set; }
        public string CancellationFee { get; set; }
        public string DateChangeFee { get; set; }
        public string Trip { get; set; }
        public string Sector { get; set; }
        public string BookingFareID { get; set; }
        public string API_AirlineID { get; set; }
        public string API_BookingFareID { get; set; }
        public int API_RefID { get; set; }
        public string API_SearchID { get; set; }
        public string Api_SessionID { get; set; }
        public string JourneySellKey { get; set; }
        public string FareSellKey { get; set; }
        public int JourneyTime { get; set; }
        public int Duration { get; set; }
        public string DepartureStationAirport { get; set; }
        public string ArrivalStationAirport { get; set; }
        public string DepartureStationName { get; set; }
        public string ArrivalStationName { get; set; }
        public string FareRule { get; set; }
        public string TempData1 { get; set; }
        public string TempData2 { get; set; }
        public string TempData3 { get; set; }
        public int Group { get; set; }
        public int FlightTime { get; set; }
        public string Distance { get; set; }
        public bool ChangeOfPlane { get; set; }
        public string ParticipantLevel { get; set; }
        public string LinkAvailability { get; set; }
        public string PolledAvailabilityOption { get; set; }
        public bool OptionalServicesIndicator { get; set; }
        public string AvailabilitySource { get; set; }
        public string AvailabilityDisplayType { get; set; }
        public string CodeshareInfoOperatingCarrier { get; set; }
        public string CodeshareInfoOperatingFlightNumber { get; set; }
        public string CodeshareInfo { get; set; }
        public int TravelTime { get; set; }
        public string BookingCode { get; set; }
        public string CabinClass { get; set; }
        public string LatestTicketingTime { get; set; }
        public string PricingMethod { get; set; }
        public string Refundable { get; set; }
        public string ETicketability { get; set; }
        public string PlatingCarrier { get; set; }
        public string ProviderCode { get; set; }
        public string Cat35Indicator { get; set; }
        public string AirPricePointKey { get; set; }
        public string SegmentRef { get; set; }
        public string FlightDetailsRefKey { get; set; }
        public string AdtAirPricingInfoKey { get; set; }
        public string ChdAirPricingInfoKey { get; set; }
        public string InfAirPricingInfoKey { get; set; }
        public string AdtFareInfoRef { get; set; }
        public string ChdFareInfoRef { get; set; }
        public string InfFareInfoRef { get; set; }
        public string AdtOptionKey { get; set; }
        public string ChdOptionKey { get; set; }
        public string InfOptionKey { get; set; }
        public string AdtTaxes { get; set; }
        public string ChdTaxes { get; set; }
        public string InfTaxes { get; set; }
        public string AdtHTR { get; set; }
        public string ChdHTR { get; set; }
        public string InfHTR { get; set; }
        public string HostTokenRef { get; set; }
        public string FareRuleInfo_Text { get; set; }
        public string AdtFareInfoRef_data { get; set; }
        public string ChdFareInfoRef_data { get; set; }
        public string InfFareInfoRef_data { get; set; }
        public string AdtBTR { get; set; }
        public string ChdBTR { get; set; }
        public string InfBTR { get; set; }
        public string Connection_O { get; set; }
        public string Connection_I { get; set; }
    }
}
